### ISSUE TITLE
Bug: Comments between textdomain and first filename line get deleted

### ISSUE THREAD

**Issue by louisroyer** [FaceDeer/update_translations#10]
How to reproduce:
- Run the script on this project: [test_mod.zip](https://github.com/minetest-tools/update_translations/files/4333190/test_mod.zip).
- Result: credits on line 2 of template.txt get deleted, comment on line 5 doesn't get deleted (both in `template.txt` and `test_mod.fr.tr`).
- Expected behavior: Credits and comments doesn't get deleted (both in `template.txt` and `test_mod.fr.tr`)

**Comment by FaceDeer** [comment]
The reason this happens is that currently comments are associated with specific lines, ensuring that should the lines get reordered the comments go with them. Comments at the top of the file aren't associated with any specific line, though, so they get lost.

Maybe a clean way to overcome this would be to define a special "file header" comment block that's at the top of the file just (underneath the textdomain line) that credits and other file-wide comments can be added to?
