### ISSUE TITLE
First line is wrong

### ISSUE THREAD

**Issue by Wuzzy2** [FaceDeer/update_translations#2]
The first line of newly created `template.txt` looks like this:

```
##### textdomain: modname #####
```
But this is syntactically wrong and doesn't seem to be recognized by Minetest.

According to `lua_api.txt` this syntax must be used:

```
# textdomain:modname
```

**Comment by louisroyer** [comment]
This has been introduced in b1a08610b1380b2cfe013d0ffd2579567541750d line 203.

**Comment by FaceDeer** [comment]
My bad, I was making header comments stand out more prominently and swept that up in my changes. Just reverted that line's change.

**Comment by louisroyer** [comment]
Fixed by ba6ef62133d200e07664a83dbdba4a26ce5f9356.
