### ISSUE TITLE
template.txt created with lots of empty lines

### ISSUE THREAD

**Issue by Wuzzy2** [FaceDeer/update_translations#3]
Excerpt from a newly created `template.txt`:

```
Degrotate Rooted Plantlike Drawtype Test Node=

Double-sized Firelike Drawtype Test Node=

Double-sized Plantlike Drawtype Test Node=

Double-sized Wallmounted Signlike Drawtype Test Node=

Double-sized Wallmounted Torchlike Drawtype Test Node=

Fencelike Drawtype Test Node=

Firelike Drawtype Test Node=

Flowing Liquid Drawtype Test Node=

Glasslike Drawtype Test Node=

Glasslike Framed Drawtype Test Node=

Glasslike Framed Optional Drawtype Test Node=
```

These empty lines are not wrong, but annoying as hell.

**Comment by FaceDeer** [comment]
For me it's the opposite, I found the crammed-together formatting to be impossible to keep track of.

I've also got a bunch of "doc" files that have large numbers of multi-line strings, those resulted in pages and pages of solid text with no way of seeing at a glance where one started and one ended. It was maddening.

I'm not sure what the best way to solve this difference of opinion will be, as I would really rather not have formatting options for this script - it'll introduce unnecessary diffs and make it hard to see what's really changed from one run to the next if people switch back and forth between double-spaced and single-spaced.

**Comment by louisroyer** [comment]
It may be possible to add empty lines only when string excess a certain size (after string and before (if this empty line is not already here)).

**Comment by FaceDeer** [comment]
That'd be fine for diffs, since the spacing would only change in that case if the line itself was changing anyway.

Since the "standard" for a terminal window width is 80 characters, maybe the threshold should be 40 characters (to allow for the length of the translated line, which will not be the same as the source line but will probably be close)? Or would that be too short? Some of the lines in Wuzzy's example are longer than that.

**Comment by Wuzzy2** [comment]
Add a command-line parameter, then.

**Comment by FaceDeer** [comment]
I'd rather settle on a standard rather than a command line parameter, though. If the script gets re-run on the same mod with different settings for the cutoff length it'd result in pointless diffs.

I won't *oppose* it, I'm just not a fan of that approach.

**Comment by FaceDeer** [comment]
I just added a threshold of 60, that seemed like it looked decent in my test cases (I've been using DFCaverns as my testbed, it has a nice mix of long and short strings over many different source files).

If you want to add a command line parameter to modify that I'll merge it, I just want a nice default I can fire-and-forget the script with and not have to sift through a bunch of extraneous whitespace diffs afterward.

**Comment by FaceDeer** [comment]
Is this issue closeable with the code in its current state?

**Comment by Wuzzy2** [comment]
If the number of excessive empty lines went down, then yes.

**Comment by FaceDeer** [comment]
Yeah, it's a lot more compact now.
